USE QUANLYGIAOVU
--9.	Lớp trưởng của một lớp phải là học viên của lớp đó.
GO
CREATE TRIGGER TRG_LOP ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	IF NOT EXISTS(SELECT * FROM INSERTED I, HOCVIEN H WHERE I.TRGLOP=H.MAHV AND I.MALOP=H.MALOP)
	BEGIN
		PRINT 'Lop truong cua lop phai la thanh vien lop do'
		ROLLBACK TRANSACTION
	END
	
END
GO

CREATE TRIGGER TRG_HOCVIEN ON HOCVIEN
FOR DELETE
AS
BEGIN
	IF EXISTS (SELECT * FROM DELETED D, LOP L WHERE D.MAHV=L.TRGLOP AND D.MALOP=D.MALOP)
	BEGIN
		PRINT 'Hoc vien hien tai la lop truong khong the xoa'
		ROLLBACK TRAN
	END
END
GO

--10. Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”.
CREATE TRIGGER TRG_KHOA ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
	IF NOT EXISTS( SELECT * FROM INSERTED I, GIAOVIEN G WHERE I.TRGKHOA=G.MAGV AND I.MAKHOA=G.MAKHOA AND G.HOCVI IN ('TS','PTS'))
	BEGIN
		PRINT'Truong khoa phai la giao vien thuoc khoa va co hoc vi "TS" hoac "PTS"'
		ROLLBACK TRANSACTION 
	END
END
GO

CREATE TRIGGER TRG_GIAOVIEN ON GIAOVIEN
FOR DELETE
AS
BEGIN
	IF EXISTS (SELECT * FROM DELETED D, KHOA K WHERE D.MAKHOA=K.MAKHOA AND D.MAGV=K.TRGKHOA)
	BEGIN
		PRINT 'Giao vien hien dang la truong khoa khong the xoa'
		ROLLBACK TRAN
	END
END
GO

-- UPDATE: Khi update không cho thay đổi MAKHOA và HOCVI phải là "TS" hoặc "PTS" của trưởng khoa
CREATE TRIGGER TRG_GIAOVIEN_UPDATE ON GIAOVIEN
FOR UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, KHOA K WHERE (I.MAGV=K.TRGKHOA AND I.MAKHOA<>K.MAKHOA))
	BEGIN
		PRINT 'Giao vien hien dang la truong khoa cua khoa nay khong the cap nhat ma khoa'
		ROLLBACK TRAN
	END
	ELSE IF EXISTS (SELECT * FROM INSERTED I, KHOA K WHERE I.MAGV=K.TRGKHOA AND I.MAKHOA=K.MAKHOA AND I.HOCVI NOT IN('TS','PTS'))
	BEGIN
		PRINT 'Giao vien la truong khoa phai co hoc vi la "TS" hoac "PTS"'
		ROLLBACK TRAN
	END
END
GO
--15. Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.
--					Thêm	Xóa		Sửa
-- GiangDay			-		-		+		
-- KetQuaThi		+		-		+
CREATE TRIGGER TRG_GIANGDAY ON GIANGDAY
FOR UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, KETQUATHI K WHERE I.MALOP=LEFT(K.MAHV,3) AND I.MAMH=K.MAMH AND I.DENNGAY>=K.NGTHI)
	BEGIN
		PRINT 'Hoc vien chi duoc thi mon hoc nao do khi lop cua hoc vien da hoc xong mon hoc nay'
		ROLLBACK TRAN
	END
END
GO

CREATE TRIGGER TRG_KETQUATHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS ( SELECT * FROM INSERTED I, GIANGDAY G WHERE LEFT(I.MAHV,3)=G.MALOP AND I.MAMH=G.MAMH AND I.NGTHI<=G.DENNGAY)
	BEGIN
		PRINT 'Hoc vien chi duoc thi mon hoc nao do khi lop cua hoc vien da hoc xong mon hoc nay'
		ROLLBACK TRAN
	END
END
GO

--16. Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.
CREATE TRIGGER TRG_GD_SLTD ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SL1HK TINYINT
	SELECT @SL1HK=(SELECT COUNT(G.MAMH) FROM GIANGDAY G, INSERTED I WHERE G.MALOP=I.MALOP AND G.HOCKY=I.HOCKY AND G.NAM=I.NAM)
	IF(@SL1HK>3)
		BEGIN
			PRINT 'Moi hoc ky cua mot nam hoc, mot lop chi duoc hoc toi da 3 mon'
			ROLLBACK TRANSACTION
		END
END
GO

--17. Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.
--				  Thêm		Xóa		Sửa
-- LOP				+		 -		 +		
-- HocVien			+		 +		 -		
CREATE TRIGGER TRG_INUP_LOP ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SISO TINYINT
	SELECT @SISO=(SELECT COUNT (H.MALOP) FROM HOCVIEN H, INSERTED I WHERE H.MALOP=I.MALOP)
	IF(@SISO <> (SELECT SISO FROM INSERTED))
	BEGIN
		UPDATE LOP
		SET SISO=@SISO WHERE MALOP=(SELECT MALOP FROM INSERTED)
		PRINT 'SI SO KHONG BANG SO LUONG HOC VIEN CUA LOP. HE THONG SE TU CAP NHAT THEO SO LUONG HOC VIEN CUA LOP HIEN CO'
	END	
END
GO

CREATE TRIGGER TRG_IN_HOCVIEN ON HOCVIEN
FOR INSERT
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, LOP L WHERE I.MALOP=L.MALOP)
	BEGIN
		UPDATE LOP 
		SET SISO = SISO + 1
		FROM LOP L JOIN INSERTED I ON L.MALOP=I.MALOP
	END
END
GO

CREATE TRIGGER TRG_DE_HOCVIEN ON HOCVIEN
FOR DELETE
AS
BEGIN
	IF EXISTS (SELECT * FROM DELETED D, LOP L WHERE D.MALOP=L.MALOP)
	BEGIN
		UPDATE LOP 
		SET SISO = SISO - 1
		FROM LOP L JOIN DELETED D ON D.MALOP=L.MALOP
	END
END
GO

--18. Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau (“A”,”A”)
--và cũng không tồn tại hai bộ (“A”,”B”) và (“B”,”A”).
CREATE TRIGGER TRG_DK ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, DIEUKIEN D WHERE I.MAMH=I.MAMH_TRUOC OR(I.MAMH=D.MAMH_TRUOC AND I.MAMH_TRUOC=D.MAMH))
	BEGIN
		PRINT 'KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
END
GO

--19.	Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau.
CREATE TRIGGER TRG_GIAOVIEN_MUCLUONG ON GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, GIAOVIEN G WHERE I.HOCHAM=G.HOCHAM AND I.HOCVI=G.HOCVI AND I.HESO=G.HESO AND I.MUCLUONG<>G.MUCLUONG)
	BEGIN
		PRINT 'MUC LUONG KHONG HOP LE: CAC GV CUNG HOC VI, HOC HAM, HE SO LUONG THI MUC LUONG BANG NHAU'
		ROLLBACK TRAN
	END
END
GO

-- 20. Học viên chỉ được thi lại (lần thi >1) khi điểm của lần thi trước đó dưới 5.
CREATE TRIGGER KQT_LANTHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM INSERTED I, KETQUATHI K WHERE I.LANTHI=1 OR (I.MAHV=K.MAHV AND I.MAMH=K.MAMH AND I.LANTHI=K.LANTHI+1 AND K.DIEM<5))
	BEGIN
		PRINT 'LOI: HOC VIEN CHI DUOC THI LAI KHI DIEM CUA LAN THI TRUOC DUOI 5'
		ROLLBACK TRAN
	END
END
GO
--Phải tồn tại lần thi trước đó
CREATE TRIGGER KQT_LANTHI_DE ON KETQUATHI
FOR DELETE
AS
BEGIN
	IF EXISTS (SELECT * FROM DELETED D, KETQUATHI K WHERE D.MAHV=K.MAHV AND D.MAMH=K.MAMH AND D.LANTHI=K.LANTHI-1)
	BEGIN
		PRINT 'LOI SO LAN THI'
		ROLLBACK TRAN
	END
END
GO

-- 21. Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước (cùng học viên, cùng môn học).
CREATE TRIGGER KQT_NGTHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, KETQUATHI K WHERE I.MAHV=K.MAHV AND I.MAMH=K.MAMH AND 
															((I.LANTHI<>1 AND K.LANTHI=I.LANTHI-1 AND I.NGTHI<=K.NGTHI) 
																		   OR(K.LANTHI=I.LANTHI+1 AND I.NGTHI>=K.NGTHI))																														)
	BEGIN
		PRINT 'LOI: NGAY THI CUA LAN THI SAU PHAI LON HON NGAY THI CUA LAN THI TRUOC'
		ROLLBACK TRAN
	END
END
GO

--22. Khi phân công giảng dạy một môn học, phải xét đến thứ tự trước sau giữa các môn học 
--(sau khi học xong những môn học phải học trước mới được học những môn liền sau).
--					Thêm	Xóa		Sửa
-- GIANGDAY			  +		 -		 +		
-- DIEUKIEN			  +		 -		 +
CREATE TRIGGER TRG_GIANGDAY_THUTU ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, GIANGDAY G, DIEUKIEN D WHERE I.MALOP=G.MALOP AND (
																	 (I.MAMH=D.MAMH AND G.MAMH=D.MAMH_TRUOC AND G.DENNGAY>=I.TUNGAY)
																  OR (G.MAMH=D.MAMH AND I.MAMH=D.MAMH_TRUOC AND I.DENNGAY>=G.TUNGAY)))
	BEGIN
		PRINT 'LOI: PHAI HOC XONG NHUNG MON PHAI HOC TRUOC MOI DUOC HOC NHUNG MON LIEN SAU'
		ROLLBACK TRAN
	END
END
GO

CREATE TRIGGER TRG_DIEUKIEN_THUTU ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, GIANGDAY G1, GIANGDAY G2 
				WHERE I.MAMH=G1.MAMH AND I.MAMH_TRUOC=G2.MAMH AND G1.MALOP=G2.MALOP AND G2.DENNGAY>=G1.TUNGAY)
	BEGIN
		PRINT 'LOI: PHAI HOC XONG NHUNG MON PHAI HOC TRUOC MOI DUOC HOC NHUNG MON LIEN SAU'
		ROLLBACK TRAN
	END
END
GO

--23. Giáo viên chỉ được phân công dạy những môn thuộc khoa giáo viên đó phụ trách.
--					Thêm	Xóa		Sửa
-- GIANGDAY			  +		 -		 +		
-- GIAOVIEN			  -		 -		 +
-- MONHOC			  -		 -		 +
CREATE TRIGGER TR_GIANGDAY_PHANCONG ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAKHOACUAMON CHAR(5), @MAKHOACUAGV CHAR(5)
	SELECT @MAKHOACUAMON= (SELECT MAKHOA FROM INSERTED I, MONHOC M WHERE I.MAMH=M.MAMH)
	SELECT @MAKHOACUAGV= (SELECT MAKHOA FROM INSERTED I, GIAOVIEN G WHERE I.MAGV=G.MAGV)
	IF( @MAKHOACUAMON <>@MAKHOACUAGV )
	BEGIN
		PRINT 'LOI: GIAO VIEN CHI DUOC PHAN CONG DAY NHUNG MON THUOC KHOA GV DO PHU TRACH'
		ROLLBACK TRAN
	END
END
GO

CREATE TRIGGER TR_GIAOVIEN_PHANCONG ON GIAOVIEN
FOR UPDATE
AS 
BEGIN
	DECLARE @MAGV CHAR(5), @MAKHOACUAGV VARCHAR(5)
	SELECT @MAGV= (SELECT MAGV FROM INSERTED), @MAKHOACUAGV= (SELECT MAKHOA FROM INSERTED)
	IF EXISTS (SELECT * FROM GIANGDAY G JOIN MONHOC M ON G.MAMH=M.MAMH WHERE G.MAGV=@MAGV AND M.MAKHOA<>@MAKHOACUAGV)
	BEGIN
		PRINT 'LOI: GIAO VIEN CHI DUOC PHAN CONG DAY NHUNG MON THUOC KHOA GV DO PHU TRACH'
		ROLLBACK TRAN
	END
END
GO

CREATE TRIGGER TR_MONHOC_PHANCONG ON MONHOC
FOR UPDATE
AS
BEGIN
	DECLARE @MAMH VARCHAR(10), @MAKHOACUAMH VARCHAR(5)
	SELECT @MAKHOACUAMH= (SELECT MAKHOA FROM INSERTED), @MAMH=(SELECT MAMH FROM INSERTED)
	IF EXISTS (SELECT * FROM GIANGDAY G JOIN GIAOVIEN GV ON G.MAGV=GV.MAGV WHERE G.MAMH=@MAMH AND GV.MAKHOA<>@MAKHOACUAMH)
	BEGIN
		PRINT 'LOI: GIAO VIEN CHI DUOC PHAN CONG DAY NHUNG MON THUOC KHOA GV DO PHU TRACH'
		ROLLBACK TRAN
	END
END
GO


