CREATE DATABASE BAITHI
USE BAITHI
--1
CREATE TABLE NHACUNGCAP(
	MANCC CHAR(5) PRIMARY KEY,
	TENNCC VARCHAR(40),
	QUOCGIA VARCHAR (40),
	LOAINCC VARCHAR(20)
)
CREATE TABLE DUOCPHAM(
	MADP CHAR(4) PRIMARY KEY,
	TENDP VARCHAR(40),
	LOAIDP VARCHAR (40),
	GIA MONEY
)
CREATE TABLE PHIEUNHAP(
	SOPN CHAR(5) PRIMARY KEY,
	NGNHAP SMALLDATETIME,
	MANCC CHAR (5) REFERENCES NHACUNGCAP(MANCC) ,
	LOAINHAP VARCHAR(20)
)
CREATE TABLE CTPN(
	SOPN CHAR(5) REFERENCES PHIEUNHAP(SOPN),
	MADP CHAR(4) REFERENCES DUOCPHAM(MADP),
	SOLUONG INT,
	CONSTRAINT FK_CTPN PRIMARY KEY (SOPN, MADP)
)
--2
INSERT INTO NHACUNGCAP VALUES ('NCC01','Phuc Hung','Viet Nam','Thuong xuyen'),
							  ('NCC02','J. B. Pharmaceuticals','India','Vang lai'),
							  ('NCC03','Sapharco','Singapore ','Vang lai')

INSERT INTO DUOCPHAM VALUES ('DP01','Thuoc ho PH','Siro','120000'),
							  ('DP02','Zecuf Herbal CouchRemedy','Vien nen','200000'),
							  ('DP03','Cotrim','Vien sui','80000')

INSERT INTO PHIEUNHAP VALUES ('00001','22/11/2017','NCC01','Noi dia'),
							  ('00002','04/12/2017','NCC03','Nhap khau'),
							  ('00003','10/12/2017','NCC02','Nhap khau')

INSERT INTO CTPN VALUES ('00001','DP01','100'),
						('00001','DP02','200'),
						('00003','DP03','543')

--3
ALTER TABLE DUOCPHAM
ADD CONSTRAINT CH_GIA CHECK (LOAIDP<>'Siro' OR GIA>100000)

--4
		--		THEM		XOA		SUA
--PHIEUNHAP		  +			-		 +
--NHACC			  -			-		 +
GO
CREATE TRIGGER TR_PHIEUNHAP ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, NHACUNGCAP N WHERE I.MANCC=N.MANCC AND N.QUOCGIA<>'Viet Nam' AND I.LOAINHAP<>'Nhap khau')
	BEGIN
		PRINT 'Cac nha cung cap tu cac quoc gia khac Viet Nam phai co loai nhap la "Nhap khau"'
		ROLLBACK TRAN
	END
END
GO

CREATE TRIGGER TR_NHACC ON NHACUNGCAP
FOR UPDATE
AS IF UPDATE(QUOCGIA)
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, PHIEUNHAP P WHERE I.MANCC=P.MANCC AND I.QUOCGIA<>'Viet Nam' AND P.LOAINHAP<>'Nhap khau')
	BEGIN
		PRINT 'Cac nha cung cap tu cac quoc gia khac Viet Nam phai co loai nhap la "Nhap khau"'
		ROLLBACK TRAN
	END
END
GO

--5
SELECT * FROM PHIEUNHAP 
WHERE MONTH(NGNHAP)=12 AND YEAR (NGNHAP)=2017
ORDER BY NGNHAP ASC

--6. Tìm dược phẩm được nhập số lượng nhiều nhất trong năm 2017 (1đ)
SELECT TOP 1 WITH TIES D.MADP, TENDP, SUM(SOLUONG) AS SOLUONGNHAP
FROM DUOCPHAM D JOIN CTPN C ON D.MADP= C.MADP
				JOIN PHIEUNHAP P ON C.SOPN =P.SOPN
				WHERE YEAR(NGNHAP)=2017
				GROUP BY D.MADP, TENDP
				ORDER BY SUM(SOLUONG) DESC

--7. Tìm dược phẩm chỉ có nhà cung cấp thường xuyên (LOAINCC là Thuong xuyen) cung cấp,
--nhà cung cấp vãng lai (LOAINCC là Vang lai) không cung cấp. (1đ).
SELECT * FROM DUOCPHAM WHERE MADP IN (
	SELECT MADP FROM CTPN C JOIN PHIEUNHAP P ON C.SOPN=P.SOPN
							JOIN NHACUNGCAP N ON P.MANCC=N.MANCC
							WHERE LOAINCC='Thuong xuyen'
	EXCEPT
	SELECT MADP FROM CTPN C JOIN PHIEUNHAP P ON C.SOPN=P.SOPN
							JOIN NHACUNGCAP N ON P.MANCC=N.MANCC
							WHERE LOAINCC='Vang lai'
	)

--8. Tìm nhà cung cấp đã từng cung cấp tất cả những dược phẩm có giá trên 100.000đ trong năm 2017 (1đ).SELECT * FROM NHACUNGCAP WHERE MANCC IN(SELECT MANCC FROM CTPN C JOIN PHIEUNHAP P ON C.SOPN=P.SOPN						 WHERE YEAR(NGNHAP)=2017						 GROUP BY MANCC						 HAVING COUNT(DISTINCT C.MADP)=(SELECT COUNT(MADP) FROM DUOCPHAM WHERE GIA>100000 ))