--1. Tạo database tên BAITHI gồm có 4 table KHACHHANG, LOAICAY, HOADON, CTHD. Tạo khóa chính, khóa ngoại cho các table đó (2đ)
CREATE DATABASE BAITHI
USE BAITHI

CREATE TABLE KHACHHANG(
	MAKH CHAR (10) PRIMARY KEY,
	TENKH VARCHAR(40),
	DIACHI VARCHAR(50),
	LOAIKH VARCHAR(30)
);
CREATE TABLE LOAICAY(
	MALC CHAR (10) PRIMARY KEY,
	TENLC VARCHAR(70),
	XUATXU VARCHAR(50),
	GIA MONEY
);
CREATE TABLE HOADON(
	SOHD CHAR (10) PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(10),
	KHUYENMAI INT,
	CONSTRAINT FK_HOADON FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);
CREATE TABLE CTHD(
	SOHD CHAR (10),
	MALC CHAR(10),
	SOLUONG INT,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MALC),
	CONSTRAINT FK_CTHD FOREIGN KEY (MALC) REFERENCES LOAICAY(MALC)
);

--2. Nhập dữ liệu cho 4 table như đề bài (1đ).
SET DATEFORMAT DMY

INSERT INTO KHACHHANG VALUES ('KH01','Liz Kim Cuong','Ha Noi','Vang lai')
INSERT INTO KHACHHANG VALUES ('KH02','Ivone Dieu Linh','Da Nang','Thuong xuyen')
INSERT INTO KHACHHANG VALUES ('KH03','Emma Nhat Khanh','TP.HCM','Vang lai')

INSERT INTO LOAICAY VALUES ('LC01','Xuong rong tai tho','Mexico','180000')
INSERT INTO LOAICAY VALUES ('LC02','Sen thach ngoc','Anh','300000')
INSERT INTO LOAICAY VALUES ('LC03','Ba mau rau','Nam Phi','270000')

INSERT INTO HOADON VALUES ('00001','22/11/2017','KH01','5')
INSERT INTO HOADON VALUES ('00002','04/12/2017','KH03','5')
INSERT INTO HOADON VALUES ('00003','10/12/2017','KH02','10')

INSERT INTO CTHD VALUES ('00001','LC01','1')
INSERT INTO CTHD VALUES ('00001','LC02','2')
INSERT INTO CTHD VALUES ('00003','LC03','5')

--3. Hiện thực ràng buộc toàn vẹn sau: Tất cả các mặt hàng xuất xứ từ nước Anh đều có giá lớn hơn 250.000đ(1đ).
ALTER TABLE LOAICAY
ADD CONSTRAINT CHECK_XXGIA CHECK(XUATXU<>'Anh' OR GIA>'250000')
GO

--4. Hiện thực ràng buộc toàn vẹn sau: Hóa đơn mua với số lượng tổng cộng lớn hơn hoặc bằng 5 đều được giảm giá 10 phần trăm. (2đ).

CREATE TRIGGER TRG_HOADON ON HOADON
FOR UPDATE
AS
BEGIN
	DECLARE @SLTONG INT, @SOHD CHAR(10), @KHUYENMAI INT
	SELECT @SOHD=(SELECT SOHD FROM INSERTED), @KHUYENMAI=(SELECT KHUYENMAI FROM INSERTED)
	SELECT @SLTONG= (SELECT SUM(CTHD.SOLUONG) FROM CTHD WHERE SOHD=@SOHD)
	IF(@SLTONG>=5 AND @KHUYENMAI<10)
		BEGIN
		PRINT 'So luong mat hang cua hoa don lon hon 5, khuyen mai phai lon hon hoac bang 10%'
		ROLLBACK TRAN
		END
END
GO

CREATE TRIGGER TRG_CTHD ON CTHD
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @SLTONG INT, @SOHD CHAR(10), @KHUYENMAI INT
	SELECT @SOHD=(SELECT SOHD FROM INSERTED)
	SELECT @KHUYENMAI=(SELECT KHUYENMAI FROM INSERTED, HOADON WHERE INSERTED.SOHD=HOADON.SOHD)
	SELECT @SLTONG= (SELECT SUM(SOLUONG) FROM CTHD WHERE SOHD=@SOHD)
	IF (@SLTONG>=5 AND @KHUYENMAI<10)
		BEGIN
		ROLLBACK TRAN
		END
END
GO

--5. Tìm tất cả các hóa đơn có ngày lập hóa đơn trong quý 4 năm 2017, sắp xếp kết quả tăng dần theo phần trăm giảm giá (1đ)
SELECT * FROM HOADON
WHERE (MONTH(NGHD) BETWEEN '10' AND '12') AND YEAR(NGHD)=2017
ORDER BY KHUYENMAI ASC 

--6. Tìm loại cây có số lượng mua ít nhất trong tháng 12 (1đ).
SELECT MALC, TENLC FROM LOAICAY
WHERE MALC = (SELECT TOP 1 WITH TIES MALC 
			FROM CTHD C, HOADON H 
			WHERE C.SOHD=H.SOHD AND MONTH(NGHD)=12
			GROUP BY MALC
			ORDER BY SUM(SOLUONG) ASC)

--7. Tìm loại cây mà cả khách thường xuyên (LOAIKH là ‘Thuong xuyen’) và khách vãng lai (LOAIKH là ‘Vang lai’) đều mua. (1đ).
DECLARE @MALC CHAR(10)
SET @MALC=(
	SELECT MALC FROM CTHD C 
					JOIN HOADON H ON C.SOHD=H.SOHD
					JOIN KHACHHANG K ON K.MAKH=H.MAKH
					WHERE LOAIKH='Thuong xuyen'
	INTERSECT
	SELECT MALC FROM CTHD C 
					JOIN HOADON H ON C.SOHD=H.SOHD
					JOIN KHACHHANG K ON K.MAKH=H.MAKH
					WHERE LOAIKH='Vang lai'		
	)
SELECT * FROM LOAICAY WHERE MALC=@MALC

--8. Tìm khách hàng đã từng mua tất cả các loại cây (1đ).
SELECT * FROM KHACHHANG 
WHERE MAKH IN( 
	SELECT MAKH FROM HOADON H JOIN CTHD C 
	ON H.SOHD = C.SOHD
	GROUP BY MAKH 
	HAVING COUNT (DISTINCT MALC)=(SELECT COUNT(MALC) FROM LOAICAY)
	)
