--1
CREATE DATABASE BAITHI
USE BAITHI

CREATE TABLE NHAPHANPHOI (
MANPP CHAR(5) PRIMARY KEY,
TENNPP VARCHAR(40),
QUOCGIA VARCHAR(40),
LOAINPP VARCHAR(20),
)
CREATE TABLE MYPHAM (
MAMP CHAR(5) PRIMARY KEY,
TENMP VARCHAR(40),
LOAIMP VARCHAR(20),
GIA MONEY
)
CREATE TABLE PHIEUNHAP(
SOPN INT PRIMARY KEY,
MANPP CHAR(5) REFERENCES NHAPHANPHOI(MANPP),
NGNHAP SMALLDATETIME,
LOAINHAP VARCHAR(20)
)
CREATE TABLE CTPN(
SOPN INT REFERENCES PHIEUNHAP(SOPN),MAMP CHAR(5) REFERENCES MYPHAM(MAMP),SOLUONG INT,PRIMARY KEY(SOPN, MAMP)
)
--2
SET DATEFORMAT DMY

INSERT INTO NHAPHANPHOI VALUES
('NPP01','Cocoon','Viet Nam','Thuong xuyen'),
('NPP02','Canmake','Nhat Ban','Vang lai'),
('NPP03','Estee Lauder','Hoa Ky','Vang lai')

INSERT INTO MYPHAM VALUES
('MP01','Sua rua mat','Dung dich','200000'),
('MP02','Son duong moi','Son','25000'),
('MP03','Mascara','Gel','330000')

INSERT INTO PHIEUNHAP VALUES
('2301','NPP01','22/11/2023','Noi dia'),
('2302','NPP03','04/12/2023','Nhap khau'),
('2303','NPP02','10/12/2023','Nhap khau')

INSERT INTO CTPN VALUES
('2301','MP01','123'),
('2301','MP02','234'),
('2303','MP03','345')

--3
ALTER TABLE MYPHAM 
ADD CONSTRAINT CH_GIAMP CHECK(LOAIMP<>'Gel' OR GIA>100000)

--4
--BANG TAM ANH HUONG
--					THEM	XOA		SUA
--PHIEUNHAP			  +		 -		 +
--NHAPHANPHOI		  -		 -		 +(QUOCGIA)
GO
CREATE TRIGGER TRG_PHIEUNHAP ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, NHAPHANPHOI P WHERE I.MANPP=P.MANPP AND P.QUOCGIA<>'Viet Nam' And I.LOAINHAP<>'Nhap khau')
	BEGIN
		PRINT 'LOI: CAC NHA PHAN PHOI CO QUOC GIA KHAC VIET NAM PHAI CO LOAI LA "NHAP KHAU"'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THANH CONG!'
	END
END
GO

CREATE TRIGGER TRG_NHAPP ON NHAPHANPHOI
FOR UPDATE
AS IF UPDATE (QUOCGIA)
BEGIN
	IF EXISTS (SELECT * FROM INSERTED I, PHIEUNHAP P WHERE I.MANPP=P.MANPP AND I.QUOCGIA<>'Viet Nam' And P.LOAINHAP<>'Nhap khau')
	BEGIN
		PRINT 'LOI: CAC NHA PHAN PHOI CO QUOC GIA KHAC VIET NAM PHAI CO LOAI LA "NHAP KHAU"'
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THANH CONG!'
	END
END
GO

--5
SELECT * FROM PHIEUNHAP
WHERE MONTH(NGNHAP)=12 AND YEAR(NGNHAP)=2023
ORDER BY NGNHAP ASC

--6
SELECT TOP 1 WITH TIES M.MAMP, TENMP, SUM(SOLUONG) AS SOLUONGMP
FROM MYPHAM M JOIN CTPN C ON M.MAMP=C.MAMP
			  JOIN PHIEUNHAP P ON P.SOPN=C.SOPN
WHERE YEAR(NGNHAP)=2023
GROUP BY M.MAMP, TENMP
ORDER BY SOLUONGMP DESC

--INSERT INTO CTPN VALUES
--('2301','MP03','230')
--DELETE CTPN WHERE SOLUONG='230'

--7

SELECT * FROM MYPHAM WHERE MAMP IN(
	SELECT M.MAMP 
	FROM MYPHAM M JOIN CTPN C ON M.MAMP=C.MAMP
				  JOIN PHIEUNHAP P ON P.SOPN=C.SOPN
				  JOIN NHAPHANPHOI N ON N.MANPP=P.MANPP
	WHERE LOAINPP='Thuong xuyen'
	EXCEPT
	SELECT M.MAMP 
	FROM MYPHAM M JOIN CTPN C ON M.MAMP=C.MAMP
				  JOIN PHIEUNHAP P ON P.SOPN=C.SOPN
				  JOIN NHAPHANPHOI N ON N.MANPP=P.MANPP
	WHERE LOAINPP='Vang lai'
	)

--8
SELECT N.MANPP, TENNPP, COUNT(M.MAMP) AS SOLUONG
FROM MYPHAM M JOIN CTPN C ON M.MAMP=C.MAMP
				  JOIN PHIEUNHAP P ON P.SOPN=C.SOPN
				  JOIN NHAPHANPHOI N ON N.MANPP=P.MANPP
WHERE YEAR(NGNHAP)=2023 AND M.GIA>200000
GROUP BY N.MANPP, TENNPP
HAVING COUNT (DISTINCT M.MAMP)=(SELECT COUNT (MAMP) FROM MYPHAM WHERE GIA>200000 )